### PR TITLE
Add stringify and tests

### PR DESCRIPTION
**Pull request by JairusSW**
Here's the final draft! Let me know if anything else needs fixing!

### CODE REVIEW

**Comment by mcollina** [comment]
Thanks!

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by JairusSW** [comment]
Awesome! Just a note, but the API is changed...

```js
tinysonic() -> tinysonic.parse()
```

**Comment by JairusSW** [comment]
You can do:
```js
parse.parse = parse
// Circular. You can use the `clones` module though.
parse.stringify = stringify
module.exports = parse
```

**Pull request merged**
